
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import sys
import os

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets")


def relative_to_assets(path: str) -> Path:
    if getattr(sys, 'frozen', False):
        # If the application is run from a bundle
        base_path = Path(sys._MEIPASS)
    else:
        # If the application is run directly from the source
        base_path = Path(__file__).parent
    return base_path / 'assets' / path

import subprocess
import threading
# Function to start the assistant in a new thread
def start_assistant():
    def run_assistant():
        subprocess.run(["python", "assistant.py"])

    assistant_thread = threading.Thread(target=run_assistant)
    assistant_thread.start()

window = Tk()
window.title("Olivia AI- Assist for you")
window.geometry("862x519")
window.configure(bg = "#3A7FF6")


canvas = Canvas(
    window,
    bg = "#3A7FF6",
    height = 519,
    width = 862,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    454.9999999999999,
    7.105427357601002e-15,
    885.9999999999999,
    519.0,
    fill="#FCFCFC",
    outline="")

button_image_1 = PhotoImage(file=relative_to_assets("frame0/button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=start_assistant,
    relief="flat"
)
button_1.place(
    x=536.9999999999999,
    y=139.0,
    width=206.0,
    height=47.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("frame0/image_1.png"))
image_1 = canvas.create_image(
    234.0000000000001,
    259.0,
    image=image_image_1
)

canvas.create_text(
    497.9999999999999,
    64.0,
    anchor="nw",
    text="Thank you for Downloading",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    561.9999999999999,
    107.0,
    anchor="nw",
    text="How can Olivia help you ?",
    fill="#000000",
    font=("Roboto Bold", 13 * -1)
)

canvas.create_text(
    724.9999999999999,
    460.0,
    anchor="nw",
    text="Support and Help",
    fill="#000000",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    808.9999999999999,
    490.0,
    anchor="nw",
    text="(BETA)",
    fill="#141414",
    font=("Roboto Bold", 13 * -1)
)

canvas.create_text(
    730.9999999999999,
    490.0,
    anchor="nw",
    text="Version 1.00",
    fill="#141414",
    font=("Roboto Bold", 13 * -1)
)
window.resizable(False, False)
window.mainloop()
